### ISSUE TITLE
character goes up when i attached the character controller to the script

### ISSUE THREAD

**Issue by superteduno** [ATd3/First-Person-Movement-Script-For-Unity#1]
please help

**Comment by D-three** [comment]
Try changing line 68 from `Velocity.y -= Gravity * -2f * Time.deltaTime;` to `Velocity.y += Gravity * -2f * Time.deltaTime;`

**Comment by D-three** [comment]
thos solves problem

> Try changing line 68 from `Velocity.y -= Gravity * -2f * Time.deltaTime;` to `Velocity.y += Gravity * -2f * Time.deltaTime;`
